name: Segundo workflow

on:
  push:

jobs:

  primeiro-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Segundo passo"
      - name: Checkout
        uses: actions/checkout@v5
      - run: date
      - run: uname -a
      - run: git --version
      - run: pwd
      - run: ls -la
      - run: cat README.md
      - run: ls
