name: Terceiro workflow

on:
  push:

env:
    CURSO: "Integração Continua"

jobs:

  primeiro-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Terceiro passo"
      - name: Checkout
        uses: actions/checkout@v5

      - name: Exibir curso
        run: echo "$CURSO"

